/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as UploadsFilenameRouteImport } from './routes/uploads.$filename'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiChatSessionsRouteImport } from './routes/api.chat.sessions'
import { Route as ApiChatSessionsSessionIdRouteImport } from './routes/api.chat.sessions.$sessionId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UploadsFilenameRoute = UploadsFilenameRouteImport.update({
  id: '/uploads/$filename',
  path: '/uploads/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatSessionsRoute = ApiChatSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatSessionsSessionIdRoute =
  ApiChatSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => ApiChatSessionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/uploads/$filename': typeof UploadsFilenameRoute
  '/api/chat/sessions': typeof ApiChatSessionsRouteWithChildren
  '/api/chat/sessions/$sessionId': typeof ApiChatSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/uploads/$filename': typeof UploadsFilenameRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/chat/sessions': typeof ApiChatSessionsRouteWithChildren
  '/api/chat/sessions/$sessionId': typeof ApiChatSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/uploads/$filename': typeof UploadsFilenameRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/chat/sessions': typeof ApiChatSessionsRouteWithChildren
  '/api/chat/sessions/$sessionId': typeof ApiChatSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/admin'
    | '/assistant'
    | '/api/chat'
    | '/api/upload'
    | '/uploads/$filename'
    | '/api/chat/sessions'
    | '/api/chat/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/register'
    | '/admin'
    | '/assistant'
    | '/api/chat'
    | '/api/upload'
    | '/uploads/$filename'
    | '/'
    | '/api/chat/sessions'
    | '/api/chat/sessions/$sessionId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/register'
    | '/_authenticated/admin'
    | '/_authenticated/assistant'
    | '/api/chat'
    | '/api/upload'
    | '/uploads/$filename'
    | '/_authenticated/'
    | '/api/chat/sessions'
    | '/api/chat/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiChatRoute: typeof ApiChatRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  UploadsFilenameRoute: typeof UploadsFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/uploads/$filename': {
      id: '/uploads/$filename'
      path: '/uploads/$filename'
      fullPath: '/uploads/$filename'
      preLoaderRoute: typeof UploadsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat/sessions': {
      id: '/api/chat/sessions'
      path: '/sessions'
      fullPath: '/api/chat/sessions'
      preLoaderRoute: typeof ApiChatSessionsRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/sessions/$sessionId': {
      id: '/api/chat/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/api/chat/sessions/$sessionId'
      preLoaderRoute: typeof ApiChatSessionsSessionIdRouteImport
      parentRoute: typeof ApiChatSessionsRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiChatSessionsRouteChildren {
  ApiChatSessionsSessionIdRoute: typeof ApiChatSessionsSessionIdRoute
}

const ApiChatSessionsRouteChildren: ApiChatSessionsRouteChildren = {
  ApiChatSessionsSessionIdRoute: ApiChatSessionsSessionIdRoute,
}

const ApiChatSessionsRouteWithChildren = ApiChatSessionsRoute._addFileChildren(
  ApiChatSessionsRouteChildren,
)

interface ApiChatRouteChildren {
  ApiChatSessionsRoute: typeof ApiChatSessionsRouteWithChildren
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatSessionsRoute: ApiChatSessionsRouteWithChildren,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiChatRoute: ApiChatRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  UploadsFilenameRoute: UploadsFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
